### ISSUE TITLE
Quick Start Problem: an unexpected keyword argument 'version_base'

### ISSUE THREAD

**Issue by Lameus** [naver/splade#50]
Hello. I've got TypeError problem with running a quick start example and during working with hf.train.py.

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/usr/splade/splade/all.py", line 6, in <module>
    from .index import index
  File "/home/usr/s/splade/splade/index.py", line 13, in <module>
    @hydra.main(config_path=CONFIG_PATH, config_name=CONFIG_NAME, version_base="1.2")
TypeError: main() got an unexpected keyword argument 'version_base'

As far as I understand. it isn't a crucial argument. However, the removing of it from @hydra.main generates SystemError: 2

**Comment by DRRV** [comment]
Hi
Can you  try to update the hydra-core package?
