### ISSUE TITLE
TypeError: main() got an unexpected keyword argument 'version_base'

### ISSUE THREAD

**Issue by rauhryan** [naver/splade#56]
Howdy, 

Sorry to bother, but I'm just trying to get the basic toy data training task to work on a fresh git clone and I'm running into the following error running:

`python3 -m splade.train`

```
Traceback (most recent call last):
  File "/home/vagrant/.conda/envs/splade_source/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vagrant/.conda/envs/splade_source/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/srv/repos/splade_source/splade/index.py", line 13, in <module>
    @hydra.main(config_path=CONFIG_PATH, config_name=CONFIG_NAME, version_base="1.2")
TypeError: main() got an unexpected keyword argument 'version_base'
```

is there something basic I'm missing?

**Comment by DRRV** [comment]
see https://github.com/naver/splade/issues/50#issue-2098431970
Can you try and update the hydra-core version?
